/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "qmesh.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(LoraCfg, LoraCfg, AUTO)


PB_BIND(TestCfg, TestCfg, AUTO)


PB_BIND(FECCfg, FECCfg, AUTO)


PB_BIND(RadioCfg, RadioCfg, AUTO)


PB_BIND(NetCfg, NetCfg, 2)


PB_BIND(POCSAGCfg, POCSAGCfg, AUTO)


PB_BIND(SysCfgMsg, SysCfgMsg, 2)


PB_BIND(ClockSetMsg, ClockSetMsg, AUTO)


PB_BIND(StatusMsg, StatusMsg, AUTO)


PB_BIND(DbgMsg, DbgMsg, 2)


PB_BIND(SerialCRCMsg, SerialCRCMsg, AUTO)


PB_BIND(BootLogMsg, BootLogMsg, AUTO)


PB_BIND(GPSMsg, GPSMsg, AUTO)


PB_BIND(LogMsg, LogMsg, AUTO)


PB_BIND(TimeMsg, TimeMsg, AUTO)


PB_BIND(SerialMsg, SerialMsg, 2)


PB_BIND(ErrorMsg, ErrorMsg, 2)


PB_BIND(DataMsg, DataMsg, 2)


PB_BIND(UpdateMsg, UpdateMsg, 2)











