#ifndef PINS_HPP
#define PINS_HPP

#if defined(MBED_OS)
#define LORA_SPI_MISO MBED_CONF_APP_LORA_SPI_MISO
#define LORA_SPI_MOSI MBED_CONF_APP_LORA_SPI_MOSI
#define LORA_SPI_CS MBED_CONF_APP_LORA_CS
#define LORA_RESET MBED_CONF_APP_LORA_RESET
#define LORA_BUSY MBED_CONF_APP_LORA_BUSY
#define LORA_DIO1 MBED_CONF_APP_LORA_DIO1
#define LORA_DIO2 MBED_CONF_APP_LORA_DIO2
#define LORA_RXCTL MBED_CONF_APP_LORA_RXCTL 
#define LORA_TXCTL MBED_CONF_APP_LORA_TXCTL 

#define OLED_SDA MBED_CONF_APP_OLED_SDA
#define OLED_SCL MBED_CONF_APP_OLED_SCL

#define RX_INT_MON MBED_CONF_APP_RX_INT_MON
#define TX_INT_MON MBED_CONF_APP_TX_INT_MON
#define INT_TRIG_MON MBED_CONF_APP_INT_TRIG_MON
#define RETRANSMIT_DIS_IN MBED_CONF_APP_RETRANSMIT_DIS_IN
#define RETRANSMIT_DIS_OUT MBED_CONF_APP_RETRANSMIT_DIS_OUT
#define RSSI_MON MBED_CONF_APP_RSSI_MON
#define FHSS_MON MBED_CONF_APP_FHSS_MON

#define QSPI_FLASH_CSN MBED_CONF_APP_QSPI_FLASH_CSN
#define QSPI_FLASH_SCK MBED_CONF_APP_QSPI_FLASH_SCK 
#define QSPI_FLASH_IO0 MBED_CONF_APP_QSPI_FLASH_IO0
#define QSPI_FLASH_IO1 MBED_CONF_APP_QSPI_FLASH_IO1
#define QSPI_FLASH_IO2 MBED_CONF_APP_QSPI_FLASH_IO2
#define QSPI_FLASH_IO3 MBED_CONF_APP_QSPI_FLASH_IO3

#define KISS_UART_TX MBED_CONF_APP_KISS_UART_TX
#define KISS_UART_RX MBED_CONF_APP_KISS_UART_RX
#define KISS_UART_EN MBED_CONF_APP_KISS_UART_EN
#define KISS_UART_ST MBED_CONF_APP_KISS_UART_ST

#define KISS_UART_TX_ALT MBED_CONF_APP_KISS_UART_TX_ALT
#define KISS_UART_RX_ALT MBED_CONF_APP_KISS_UART_RX_ALT
#define KISS_UART_EN_ALT MBED_CONF_APP_KISS_UART_EN_ALT
#define KISS_UART_ST_ALT MBED_CONF_APP_KISS_UART_ST_ALT

#define LED_1 LED1
#define LED_2 LED2
#define LED_3 LED3

#elif defined(ESP_IDF)

#endif

#endif /* PINS_HPP */