/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "qmesh.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(LoraCfg, LoraCfg, AUTO)


PB_BIND(Testing, Testing, AUTO)


PB_BIND(FECCfg, FECCfg, AUTO)


PB_BIND(SysCfgMsg, SysCfgMsg, AUTO)


PB_BIND(ClockSetMsg, ClockSetMsg, AUTO)


PB_BIND(StatusMsg, StatusMsg, AUTO)


PB_BIND(SerialMsg, SerialMsg, AUTO)


PB_BIND(DataMsg, DataMsg, 2)






