# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qmesh.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='qmesh.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bqmesh.proto\x1a\x0cnanopb.proto\"F\n\x07LoraCfg\x12\n\n\x02\x62w\x18\x01 \x01(\x05\x12\n\n\x02\x63r\x18\x02 \x01(\x05\x12\n\n\x02sf\x18\x03 \x01(\x05\x12\x17\n\x0fpreamble_length\x18\x04 \x01(\x05\";\n\x07Testing\x12\x14\n\x0c\x63w_test_mode\x18\x01 \x01(\x08\x12\x1a\n\x12preamble_test_mode\x18\x02 \x01(\x08\"\x88\x01\n\x06\x46\x45\x43\x43\x66g\x12\x11\n\tconv_rate\x18\x01 \x01(\x05\x12\x12\n\nconv_order\x18\x02 \x01(\x05\x12\x14\n\x0crs_num_roots\x18\x03 \x01(\x05\"A\n\x04Type\x12\x08\n\x04NONE\x10\x00\x12\x0e\n\nINTERLEAVE\x10\x01\x12\x08\n\x04\x43ONV\x10\x02\x12\x07\n\x03RSV\x10\x03\x12\x0c\n\x08RSVGOLAY\x10\x04\"\x8b\x01\n\tSysCfgMsg\x12\x11\n\tfrequency\x18\x01 \x01(\x05\x12\x1a\n\x0b\x66requencies\x18\x02 \x03(\x05\x42\x05\x92?\x02\x10\x10\x12\x1a\n\x08lora_cfg\x18\x03 \x01(\x0b\x32\x08.LoraCfg\x12\x19\n\x07testing\x18\x04 \x01(\x0b\x32\x08.Testing\x12\x18\n\x07\x66\x65\x63_cfg\x18\x05 \x01(\x0b\x32\x07.FECCfg\"\x1b\n\x0b\x43lockSetMsg\x12\x0c\n\x04time\x18\x01 \x01(\r\"^\n\tStatusMsg\x12\x0f\n\x07tx_full\x18\x01 \x01(\x08\x12\x0c\n\x04time\x18\x02 \x01(\r\"2\n\x06Status\x12\x0b\n\x07\x42OOTING\x10\x00\x12\x0e\n\nMANAGEMENT\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\"\x9e\x01\n\tSerialMsg\x12\x1b\n\x07sys_cfg\x18\x01 \x01(\x0b\x32\n.SysCfgMsg\x12\x1f\n\tclock_set\x18\x02 \x01(\x0b\x32\x0c.ClockSetMsg\x12\x1a\n\x06status\x18\x03 \x01(\x0b\x32\n.StatusMsg\"7\n\x04Type\x12\n\n\x06\x43ONFIG\x10\x00\x12\x08\n\x04\x44\x41TA\x10\x01\x12\r\n\tCLOCK_SET\x10\x02\x12\n\n\x06STATUS\x10\x03\"t\n\x07\x44\x61taMsg\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x11\n\tstream_id\x18\x02 \x01(\r\x12\x0b\n\x03ttl\x18\x03 \x01(\r\x12\x0e\n\x06sender\x18\x04 \x01(\r\x12\x12\n\nsym_offset\x18\x05 \x01(\r\x12\x17\n\x07payload\x18\x06 \x01(\x0c\x42\x06\x92?\x03\x08\x80\x02\x62\x06proto3')
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])



_FECCFG_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='FECCfg.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERLEAVE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONV', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RSV', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RSVGOLAY', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=234,
  serialized_end=299,
)
_sym_db.RegisterEnumDescriptor(_FECCFG_TYPE)

_STATUSMSG_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='StatusMsg.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BOOTING', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MANAGEMENT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=516,
  serialized_end=566,
)
_sym_db.RegisterEnumDescriptor(_STATUSMSG_STATUS)

_SERIALMSG_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='SerialMsg.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONFIG', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOCK_SET', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=672,
  serialized_end=727,
)
_sym_db.RegisterEnumDescriptor(_SERIALMSG_TYPE)


_LORACFG = _descriptor.Descriptor(
  name='LoraCfg',
  full_name='LoraCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bw', full_name='LoraCfg.bw', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cr', full_name='LoraCfg.cr', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sf', full_name='LoraCfg.sf', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preamble_length', full_name='LoraCfg.preamble_length', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=99,
)


_TESTING = _descriptor.Descriptor(
  name='Testing',
  full_name='Testing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cw_test_mode', full_name='Testing.cw_test_mode', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preamble_test_mode', full_name='Testing.preamble_test_mode', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=160,
)


_FECCFG = _descriptor.Descriptor(
  name='FECCfg',
  full_name='FECCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='conv_rate', full_name='FECCfg.conv_rate', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conv_order', full_name='FECCfg.conv_order', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rs_num_roots', full_name='FECCfg.rs_num_roots', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FECCFG_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=299,
)


_SYSCFGMSG = _descriptor.Descriptor(
  name='SysCfgMsg',
  full_name='SysCfgMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frequency', full_name='SysCfgMsg.frequency', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frequencies', full_name='SysCfgMsg.frequencies', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\002\020\020'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lora_cfg', full_name='SysCfgMsg.lora_cfg', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='testing', full_name='SysCfgMsg.testing', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fec_cfg', full_name='SysCfgMsg.fec_cfg', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=441,
)


_CLOCKSETMSG = _descriptor.Descriptor(
  name='ClockSetMsg',
  full_name='ClockSetMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='ClockSetMsg.time', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=470,
)


_STATUSMSG = _descriptor.Descriptor(
  name='StatusMsg',
  full_name='StatusMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tx_full', full_name='StatusMsg.tx_full', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='StatusMsg.time', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STATUSMSG_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=566,
)


_SERIALMSG = _descriptor.Descriptor(
  name='SerialMsg',
  full_name='SerialMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sys_cfg', full_name='SerialMsg.sys_cfg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clock_set', full_name='SerialMsg.clock_set', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='SerialMsg.status', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SERIALMSG_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=569,
  serialized_end=727,
)


_DATAMSG = _descriptor.Descriptor(
  name='DataMsg',
  full_name='DataMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DataMsg.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stream_id', full_name='DataMsg.stream_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ttl', full_name='DataMsg.ttl', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender', full_name='DataMsg.sender', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sym_offset', full_name='DataMsg.sym_offset', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='DataMsg.payload', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\003\010\200\002'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=729,
  serialized_end=845,
)

_FECCFG_TYPE.containing_type = _FECCFG
_SYSCFGMSG.fields_by_name['lora_cfg'].message_type = _LORACFG
_SYSCFGMSG.fields_by_name['testing'].message_type = _TESTING
_SYSCFGMSG.fields_by_name['fec_cfg'].message_type = _FECCFG
_STATUSMSG_STATUS.containing_type = _STATUSMSG
_SERIALMSG.fields_by_name['sys_cfg'].message_type = _SYSCFGMSG
_SERIALMSG.fields_by_name['clock_set'].message_type = _CLOCKSETMSG
_SERIALMSG.fields_by_name['status'].message_type = _STATUSMSG
_SERIALMSG_TYPE.containing_type = _SERIALMSG
DESCRIPTOR.message_types_by_name['LoraCfg'] = _LORACFG
DESCRIPTOR.message_types_by_name['Testing'] = _TESTING
DESCRIPTOR.message_types_by_name['FECCfg'] = _FECCFG
DESCRIPTOR.message_types_by_name['SysCfgMsg'] = _SYSCFGMSG
DESCRIPTOR.message_types_by_name['ClockSetMsg'] = _CLOCKSETMSG
DESCRIPTOR.message_types_by_name['StatusMsg'] = _STATUSMSG
DESCRIPTOR.message_types_by_name['SerialMsg'] = _SERIALMSG
DESCRIPTOR.message_types_by_name['DataMsg'] = _DATAMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoraCfg = _reflection.GeneratedProtocolMessageType('LoraCfg', (_message.Message,), dict(
  DESCRIPTOR = _LORACFG,
  __module__ = 'qmesh_pb2'
  # @@protoc_insertion_point(class_scope:LoraCfg)
  ))
_sym_db.RegisterMessage(LoraCfg)

Testing = _reflection.GeneratedProtocolMessageType('Testing', (_message.Message,), dict(
  DESCRIPTOR = _TESTING,
  __module__ = 'qmesh_pb2'
  # @@protoc_insertion_point(class_scope:Testing)
  ))
_sym_db.RegisterMessage(Testing)

FECCfg = _reflection.GeneratedProtocolMessageType('FECCfg', (_message.Message,), dict(
  DESCRIPTOR = _FECCFG,
  __module__ = 'qmesh_pb2'
  # @@protoc_insertion_point(class_scope:FECCfg)
  ))
_sym_db.RegisterMessage(FECCfg)

SysCfgMsg = _reflection.GeneratedProtocolMessageType('SysCfgMsg', (_message.Message,), dict(
  DESCRIPTOR = _SYSCFGMSG,
  __module__ = 'qmesh_pb2'
  # @@protoc_insertion_point(class_scope:SysCfgMsg)
  ))
_sym_db.RegisterMessage(SysCfgMsg)

ClockSetMsg = _reflection.GeneratedProtocolMessageType('ClockSetMsg', (_message.Message,), dict(
  DESCRIPTOR = _CLOCKSETMSG,
  __module__ = 'qmesh_pb2'
  # @@protoc_insertion_point(class_scope:ClockSetMsg)
  ))
_sym_db.RegisterMessage(ClockSetMsg)

StatusMsg = _reflection.GeneratedProtocolMessageType('StatusMsg', (_message.Message,), dict(
  DESCRIPTOR = _STATUSMSG,
  __module__ = 'qmesh_pb2'
  # @@protoc_insertion_point(class_scope:StatusMsg)
  ))
_sym_db.RegisterMessage(StatusMsg)

SerialMsg = _reflection.GeneratedProtocolMessageType('SerialMsg', (_message.Message,), dict(
  DESCRIPTOR = _SERIALMSG,
  __module__ = 'qmesh_pb2'
  # @@protoc_insertion_point(class_scope:SerialMsg)
  ))
_sym_db.RegisterMessage(SerialMsg)

DataMsg = _reflection.GeneratedProtocolMessageType('DataMsg', (_message.Message,), dict(
  DESCRIPTOR = _DATAMSG,
  __module__ = 'qmesh_pb2'
  # @@protoc_insertion_point(class_scope:DataMsg)
  ))
_sym_db.RegisterMessage(DataMsg)


_SYSCFGMSG.fields_by_name['frequencies']._options = None
_DATAMSG.fields_by_name['payload']._options = None
# @@protoc_insertion_point(module_scope)
