beacon_msg: KG5VBY Beacon Test
# LoRa Parameters
preamble_length: 16
preamble_test_mode: false
sf: 7 
bw: 2
cr: 0
num_offsets: 4
payload_length: 34
cw_test_mode: false
# RF Parameters
tcxo_time_us: 1000.0
frequencies:
        - 424000000
        - 425000000
        - 426000000
frequency: 426000000
# FEC Parameters
fec_algo: 4
conv_order: 7
conv_rate: 2
rs_num_roots: 8
# Testing and Logging
fec_test_mode: false
gps_en: false
log_boot: true
log_packets: false
# Watchdog
watchdog_timer_en: true
# Whether to use random or Walsh codes
walsh_codes: false 
# Invert bits before transmission as an anti-interference thing
invert_bits: true
# codec2 stuff
voice_frames_per_frame: 4
codec2_bitrate: 700
# Settings for the ESP32 modules
esp0_exists: true
esp0_isbt: false
esp0_isap: true
esp0_ser_name: bt0
esp0_bt_name: QMesh-BT0
esp0_bt_pin: "0000"
esp0_wifi_chan: "6"
esp0_ssid: QMesh-WiFi0
esp0_pass: password
esp0_ip_addr: 192.168.10.1
esp0_gateway_addr: 192.168.10.1
esp0_subnet_addr: 255.255.255.0
esp0_dhcp_range_lo: 192.168.10.10
esp0_dhcp_range_hi: 192.168.10.50
esp0_multicast_addr: 224.0.0.0
esp0_local_port: "8880"
esp0_remote_port: "8881"

esp1_exists: false
esp1_isbt: true
esp1_isap: false
esp1_ser_name: bt1
esp1_bt_name: QMesh-BT1
esp1_bt_pin: "0000"
esp1_wifi_chan: "6"
esp1_ssid: QMesh-WiFi1
esp1_pass: password
esp1_ip_addr: 192.168.20.1
esp1_gateway_addr: 192.168.20.1
esp1_subnet_addr: 255.255.255.0
esp1_dhcp_range_lo: 192.168.20.10
esp1_dhcp_range_hi: 192.168.20.50
esp1_multicast_addr: 224.0.0.1
esp1_local_port: "8880"
esp1_remote_port: "8881"

